version: 2
sources:
  - name: raw
    database: "{{ env_var('SNOWFLAKE_DATABASE', 'RETAIL') }}"
    schema: RAW
    tables: [{name: orders}]
models:
  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
  - name: fct_daily_sales
    columns:
      - name: order_date
        tests: [not_null, unique]